### ISSUE TITLE
Wrong 'ret' value

### ISSUE THREAD

**Issue by fed-franz** [blockai/testnet-faucet#1]
I'm trying to use this lib both as CLI and as a library, and it works.
However the returned structure does not correspond to the just done transaction.
Instead a previous one is returned, and usually keeps returning this same tx data for some times.

**Comment by olalonde** [comment]
I'm not sure how to fix that or what you are expecting as a return value. I'd however be happy to merge a pull request.

**Comment by fed-franz** [comment]
I would expect the data of the transaction that just transferred me the coins,
not some other random transaction :)
